module.exports = [
   'Addicted To Decorating',
   'The Inspired Room',
   'Today’s Homeowner',
   'Confessions Of A Serial DIYer',
   'Remodelaholic',
   'Smitten Kitchen',
   'Simply Recipes',
   'Sprouted Kitchen',
   'Cookie And Kate',
   'I Am A Food Blog',
   'Drew Binsky',
   'Dan Flying Solo',
   'Lili’s Travel Plans',
   'My Life’s A Movie',
   'Travel Break',
   'Money Saving Mom',
   'Get Rich Slowly',
   'Money Ning',
   'Wallet Squirrel',
   'NerdWallet',
   'TechCrunch',
   'Futurism',
   'Android Authority',
   'HackerNoon',
   'Business Insider',
   'Zen Habits',
   '4-Hour Workweek',
   'Jack Canfield',
   'Thrive Global',
   'Nerd Fitness Blog'
];